### ISSUE TITLE
Googleスプレッドシートの時刻表のシミュレート結果表記について

### ISSUE THREAD

**Issue by h5y1m141** [chooyan-eng/code-your-ruby#4]
[特定の時間での時刻表のシミュレート結果はスプレッドシート](https://docs.google.com/spreadsheets/d/1nvbqg04G4nXkpEchBWCrGI6gdMJI6IEW6qNMi1Vj0W0/edit#gid=0)をまとめていただいてるかと思います。

11時10分出発の場合に

- SS3 中井 なかい
- SS14 東伏見 ひがしふしみ

で、急行待ちをするはずかと思います。

以下囲ったように、東伏見の方は通常の時間しか待ってないようで結果が正しくないように見えるのですが、私の認識間違いでしょうか？

![2018-01-08 9 15 17](https://user-images.githubusercontent.com/950924/34655966-9831e98c-f455-11e7-9c84-e0d90188a5bc.png)

ちなみに、私が作った実装での結果だとこんな感じになりました！

駅   |  到着 | 出発
----|---|--
SS0  |   なし  | 11:10
SS1  |11:13 | 11:14
SS2  |11:17 | 11:18
SS3  |11:21 | 11:23
SS4  |11:26 | 11:27
SS5  |11:30 | 11:31
SS6  |11:34 | 11:35
SS7  |11:38 | 11:39
SS8  |11:42 | 11:43
SS9  |11:46 | 11:47
SS10 |11:50 | 11:51
SS11 |11:54 | 11:55
SS12 |11:58 | 11:59
SS13 |12:02 | 12:03
SS14 |12:06 | 12:08
SS15 |12:11 | 12:12
SS16 |12:15 | 12:16
SS17 |12:19 | 12:20
SS18 |12:23 | 12:24
SS19 |12:27 | 12:28
SS20 |12:31 | 12:32
SS21 |12:35 | 12:36

**Comment by chooyan-eng** [comment]
@h5y1m141 さん

ちょっと仕様が分かりづらいですが、これはスプレッドシートが正しいです。

各駅停車が後続の急行列車の通過待ちをする場合の仕様は __「後続の急行列車が現在の駅を出発（通過）する1分後に出発」__ です。

今回東伏見駅で通過待ちをする急行列車（H列）は12:06に東伏見駅を通過しますので、その1分後に出発（つまり記載の12:07に出発）で間違いありません。  

この東伏見の例のように、 __後続の急行列車と到着が同時だった場合__ は結果として通常の待ち時間と同じになってしまいますが、そこは仕様通りということにしていただければと思います。

**Comment by chooyan-eng** [comment]
そしてこの仕様、実装できたのですね！嬉しいです！（自分は途中でストップ中、、、）

**Comment by h5y1m141** [comment]
@chooyan-eng 

> 東伏見の例のように、 後続の急行列車と到着が同時だった場合 は結果として通常の待ち時間と同じになってしまいますが、そこは仕様通り

なるほど～ そういうことなのですね！

仕様把握できたので、その箇所の修正してPR頑張って作ります〜

> そしてこの仕様、実装できたのですね！嬉しいです！（自分は途中でストップ中、、、）

年末＆年始に[オブジェクト指向設計実践ガイド～Rubyでわかる 進化しつづける柔軟なアプリケーションの育て方](http://gihyo.jp/book/2016/978-4-7741-8361-9)というとても良い本を読んでいて、今回みたいなお題が、ちょうど本の内容を実践するのにちょうどよかったので実装してみました 😄

**Comment by chooyan-eng** [comment]
おー、こんな本があるのですね！
これ読んだ上で @h5y1m141 さんのプルリク見たら勉強になりそうですね！ちょっと読んでみます。

**Comment by chooyan-eng** [comment]
このissueの内容は解決したと思いますので、クローズさせていただきます。
