### ISSUE TITLE
ガショヲショ : fizz_buzz.md の typo?

### ISSUE THREAD

**Issue by gouf** [chooyan-eng/code-your-ruby#7]
Typo がありそうです。よくよく見てみると意味不明なので以下報告します。

* 該当箇所：[specification/fizz_buzz.md](https://github.com/chooyan-eng/code-your-ruby/blob/1510dd2aa5c3f27a0fd5c01574a08e9dbf93c02e/specification/fizz_buzz.md) 参加手順についての記述
* 発見方法：Web ブラウザのページ内検索機能を用いて「が書を書」を検索する

**Comment by chooyan-eng** [comment]
ご報告ありがとうございます！
修正しました。
